### PR TITLE
Add blog search and redesign of navbar.

### PR DESCRIPTION
**Pull request by FionaDL**
This PR adds a search bar to the navbar of the the blog. It also removed casper icons and add icomoon icons instead. It also changes the navbar of the blog to be more inline with fastruby.io as well as the ombulabs.com blog design. 

This PR works hand in hand with https://github.com/ombulabs/fastruby.io/pull/221

Both of these stories are addressed here:
https://www.pivotaltracker.com/story/show/172463087 
https://www.pivotaltracker.com/story/show/173277617

Before screenshot (large screen):
Screen Shot 2020-09-11 at 12 51 49 PM
After (large screen):
Screen Shot 2020-09-11 at 12 52 29 PM
Before medium screen:
Screen Shot 2020-09-11 at 12 52 04 PM
After medium screen:
Screen Shot 2020-09-11 at 12 53 08 PM
Before small screen:
Screen Shot 2020-09-11 at 12 52 13 PM
After small screen:
Screen Shot 2020-09-11 at 12 53 19 PM

### CODE REVIEW

**Comment by cleicar** [comment]
@FionaDL when in the results page the link to "FastRuby Blog" on top isn't working.

Screen Shot 2020-09-16 at 12 39 13

**Review by cleicar — CHANGES_REQUESTED** [review]
@FionaDL this looks good, but I found an issue.

**Comment by FionaDL** [comment]
@cleicar I added the correct link over on this PR ombulabs/fastruby.io#221 . Let me know if you find anything else :)

**Review by cleicar — APPROVED** [review]
This is great @FionaDL. Thanks!

**Pull request merged**
