### PR TITLE
[#172290354 ] Duplicated meta descriptions

### PR DESCRIPTION
**Pull request by nykka**
**IMPORTANT: blog posts must be approved by two reviewers before they can be published, one of which must be a native English speaker.**

Pivotal Story Reference: https://www.pivotaltracker.com/story/show/172290354

This PR:
- Refactors description meta tag to show a different content in each page

```
{%- capture description -%}
    {% if page.meta.description -%} {{page.meta.description}} {{page_number}}
    {%- elsif page.category -%} Articles on {{page.category | titleize | replace: '-',' '}} in the {{site.description}} blog. {{page_number}}
    {%- elsif page.is_authors_index -%} Articles by {{ site.authors[page.author].display_name }} {{page_number}}
    {%- elsif page -%} {{ page.excerpt | strip_html }} {{page_number}}
    {%- else -%} {{ site.meta_description }} {{page_number}}
    {%- endif -%}
{%- endcapture -%}
```

### CODE REVIEW

**Comment by nykka** [comment]
@lubc Do you know if we can deploy this to staging and check the duplicated meta in semrush?

**Comment by ABizzinotto** [comment]
@lubc did you see Vero's comment?

**Comment by lubc** [comment]
> @lubc Do you know if we can deploy this to staging and check the duplicated meta in semrush?
@nykka hm, we probably have to setup that. have you tested it locally?

**Comment by nykka** [comment]
> > @lubc Do you know if we can deploy this to staging and check the duplicated meta in semrush?
> 
> @nykka hm, we probably have to setup that. have you tested it locally?

@lubc Yup

**Comment by lubc** [comment]
@nykka Sorry for the delay, I just deployed this branch to staging and created a new project in semrush for FastRuby staging (https://www.semrush.com/siteaudit/campaign/3949736/review/#overview)

Looking at it in staging, I don't see any meta description value:
Screen Shot 2020-07-16 at 12 50 31 PM

Can you check that? Thanks!

**Comment by nykka** [comment]
@lubc , Can you take a look now https://fastrubyio-staging.herokuapp.com/blog/authors/abizzinotto ?

**Comment by lubc** [comment]
@nykka I don't see that you pushed any new change here

**Comment by nykka** [comment]
> @nykka I don't see that you pushed any new change here

@arielj re deployed Staging again

**Comment by lubc** [comment]
Just redeployed and it shows the description now 👍

**Comment by ABizzinotto** [comment]
@nykka could you merge this PR please? Thanks!

**Pull request merged**
