### PR TITLE
Fix branding for blog

### PR DESCRIPTION
**Pull request by cleicar**
Hey guys,

This PR updates the wrong references to FastRuby.io brand.

RE: https://www.pivotaltracker.com/n/projects/2200403/stories/175319881

### CODE REVIEW

**Review by etagwerker — CHANGES_REQUESTED** [review]
@cleicar Looks good, but I think you missed one in this file: 

- https://github.com/fastruby/blog/blob/main/_posts/2020-08-26-rails-upgrades-simplecov.markdown

**Comment by FionaDL** [comment]
@cleicar looks good, saw the same one as Ernesto. I was also wondering if we should be updating Ombu Labs to "OmbuLabs" here as well. Or else we can create a new story for that.

**Comment by cleicar** [comment]
Thanks, @etagwerker. I just fixed the one you mentioned.

@FionaDL yes, we should fix this in a new story.

**Review by etagwerker — APPROVED** [review]
Great, thanks!

**Pull request merged**
